from io import BytesIO
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor, grey
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime


# ===========================
# Footer on every page
# ===========================

class FooterCanvas(canvas.Canvas):

    def draw_footer(self):

        self.saveState()

        self.setFont("Helvetica", 8)

        # Light grey text
        self.setFillColorRGB(0.72, 0.72, 0.72)

        self.drawCentredString(
            300,
            18,
            "Generated by Koushik Mangalagiri's AI"
        )

        self.restoreState()

    def showPage(self):
        self.draw_footer()
        super().showPage()

    def save(self):
        self.draw_footer()
        super().save()


# ===========================
# Create PDF
# ===========================

def create_pdf(report_text, job_role):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER
    title.textColor = HexColor("#D4AF37")

    heading = styles["Heading2"]
    heading.textColor = HexColor("#D4AF37")

    normal = styles["BodyText"]

    story = []

    # =======================
    # Title
    # =======================

    story.append(
        Paragraph(
            "Resume Intelligence",
            title
        )
    )

    story.append(
        Paragraph(
            "<b>Professional AI Resume Analysis Report</b>",
            normal
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    # =======================
    # Job Role
    # =======================

    story.append(
        Paragraph(
            f"<b>Target Role:</b> {job_role}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y | %I:%M %p')}",
            normal
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            "<b>AI Resume Analysis</b>",
            heading
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    # Split report into paragraphs

    for line in report_text.split("\n"):

        if line.strip() == "":
            story.append(Spacer(1, 0.08 * inch))
        else:
            story.append(
                Paragraph(
                    line.replace("•", "&bull;"),
                    normal
                )
            )

    doc.build(
        story,
        canvasmaker=FooterCanvas
    )

    pdf = buffer.getvalue()

    buffer.close()

    return pdf